# `=== Atelier Numpy ===`

### `=== Contexte ===`

Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales

### `=== Partie 1 : Listes Python vs tableaux NumPy ===`

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

##### `1.1 Création d'une liste Python stockant ces températures`

In [2]:
# liste standard de python
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8]
print("liste stadard de python:")
print(temperatures)

liste stadard de python:
[24.5, 25.1, 26.3, 27.0, 25.8]


##### `=== 1.2 Création d'un tableau NumPy équivalent stockant ces températures ===`

In [6]:
import numpy as np

# tableau numpy
numpy_tableau = np.array(temperatures)
print("Tableau numpy")
print(numpy_tableau)

Tableau numpy
[24.5 25.1 26.3 27.  25.8]


##### `=== 1.3 Multiplication par 2 sur ces deux collections === `

In [21]:
import time

# Multiplication avec la liste pyrthon (boucle for)
start_time1 = time.time()
temperature_x2 = []
for temp in temperatures:
     temperature_x2.append(temp * 2)

print(f"Multiplication avec les listes python: \n {temperatures_x2} \n Temps d'execution: {time.time() - start_time1:.6f} \n") 

# Multiplication avec les tableaux numpy (operation vectoriel)
start_time2 = time.time()
print(f"Multiplication du tableau numpy: \n {numpy_tableau*2} \n Temps d'execution {time.time() - start_time2:.6f}")

Multiplication avec les listes python: 
 [49.0, 50.2, 52.6, 54.0, 51.6] 
 Temps d'execution: 0.000097 

Multiplication du tableau numpy: 
 [49.  50.2 52.6 54.  51.6] 
 Temps d'execution 0.000257


#### `=== 1.4 Observation ===`

On constate qu'avec le calcul sur les listes standards de python, pour ce cas, que la durée d'execution est plus courte qu'avec le tableau `NumPy` mais en terme ligne de code, la multiplication avec le tableau numpy est beaucoup plus optimisé (1 ligne)

### `=== Partie 2 – Création des données ===`

##### `2.1 Tableau représentant les mesures de température de 10 capteurs, initialement à zéro`

In [25]:
# Numpy deja importé en haut !
temps_10_capteurs_0 = np.zeros(10)
print(temps_10_capteurs_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### `2.2  Création d'un tableau contenant 10 valeurs égales à 1.`

In [26]:
# Numpy deja importé en haut !
temps_10_capteurs_1 = np.ones(10)
print(temps_10_capteurs_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### `2.3 Création d'un tableau de 10 valeurs initialisées à 25.`

In [220]:
temps_10_capteurs_25 = np.full((10), 25)
print(temps_10_capteurs_25)

[25 25 25 25 25 25 25 25 25 25]


#### `3.4 Création  d'une matrice identité de taille 5 × 5.`

In [35]:
identite = np.eye(5)
print(identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### `3.5 Création des 24 heures (de 0 à 23) de mesure d'une journée`

In [36]:
temps_24_heures = np.arange(24)
print(temps_24_heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


##### `3.6 Création de 10 valeurs régulièrement réparties entre 20 °C et 30 °C`

In [222]:
temps_20_40_c = np.linspace(20, 30,10)
print(temps_20_40_c)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


##### `3.7 Création de 100 mesures de températures aleatoires, reproductible`

In [41]:
from numpy import random

# On fixe la graine (seed) pour rendre le resultat reproductible
rng = np.random.default_rng(seed=42)
# On genere 100 temperatures 
temperatures_alea = rng.uniform(low=20, high=30, size=100)
print(temperatures_alea)

[27.73956049 24.3887844  28.5859792  26.97368029 20.94177348 29.75622352
 27.61139702 27.86064305 21.28113633 24.50385938 23.70798024 29.26764989
 26.4386512  28.22761613 24.43414199 22.27238722 25.54584787 20.63817256
 28.27631172 26.31664399 27.5808774  23.54525968 29.70698024 28.93121121
 27.78383497 21.94638708 24.66721004 20.43803766 21.54289492 26.83048953
 27.44762156 29.67509732 23.25825358 23.70459706 24.69555811 21.89471359
 21.29921505 24.75704926 22.26909349 26.69813995 24.37151919 28.32678196
 27.00265102 23.12366641 28.32259801 28.04764357 23.87478379 22.88328104
 26.82495504 21.39752484 21.99908202 20.0736227  27.86924378 26.64850857
 27.05165379 27.80729031 24.58915776 25.68741196 21.39796998 21.14530074
 26.68402962 24.71096206 25.65236106 27.64998857 26.3471832  25.53579401
 25.59207161 23.03950098 20.30817835 24.36717389 22.14584673 24.08528644
 28.53403073 22.33939486 20.58302742 22.81383892 22.93593758 26.61916515
 25.57032152 27.83898209 26.6431354  24.06386861 28

#### `Partie 3 – Exploration des tableaux`

##### `3.1 Créeation d'un tableau représentant les 24 températures d'une journée de façon aléatoire :`

In [89]:
alea = rng.uniform(low=20, high=45, size=24)
 

print(alea)

[24.26482421 43.12800296 34.52652849 28.67174511 34.77288729 20.57009678
 43.96398033 32.05758592 39.56838068 22.06825    32.16645827 32.26767486
 43.44566137 34.29320131 31.83723503 26.67439158 28.28922493 33.01681006
 30.97278651 20.540302   40.6572981  42.4040193  23.50622722 33.85090359]


##### `3.2 Propriétes du tableau`

`a) nombre de dimensions ;`

In [90]:
print(f"Nombre de dimension: {alea.ndim}")

Nombre de dimension: 1


`b) nombre de valeurs ;`

In [91]:
print(f"Nombre de valeur: {alea.size}")

Nombre de valeur: 24


`c) type des données ;`

In [92]:
print(f"Type des données: {alea.dtype}")

Type des données: float64


`d) forme du tableau.`

In [93]:
print(f"Forme du tableau: {alea.shape}")

Forme du tableau: (24,)


#### `Partie 4 – Indexation et slicing`

Considérant le tableau représentant les 24 températures d'une journée, afficher :

`1) la première mesure ;`

In [94]:
print(f"La première mesure: {alea[0]:.3f}")

La première mesure: 24.265


`2) la dernière mesure ;`

In [95]:
print(f"La dernière mesure: {alea[-1]:.3f}")

La dernière mesure: 33.851


`3) la température de 8h ;`

In [96]:
print(f"La temperature de 8h: {alea[7]:.3f}")

La temperature de 8h: 32.058


`4) les températures de 8h à 12h ;`

In [97]:
print(f"Les températures de 8h à 12h: {alea[7:12]}")

Les températures de 8h à 12h: [32.05758592 39.56838068 22.06825    32.16645827 32.26767486]


`5) les températures des 6 premières heures ;`

In [98]:
print(f"Temperatures des 6 premiers heures: {alea[:6]}")

Temperatures des 6 premiers heures: [24.26482421 43.12800296 34.52652849 28.67174511 34.77288729 20.57009678]


`6) les températures des heures paires.`

In [99]:
index_pair = np.array([i for i in range(23) if i % 2 == 0])
print(alea[index_pair])

[24.26482421 34.52652849 34.77288729 43.96398033 39.56838068 32.16645827
 43.44566137 31.83723503 28.28922493 30.97278651 40.6572981  23.50622722]


### `Partie 5 – Filtrage booléen`

Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les
situations inhabituelles.

`1) Afficher les températures supérieures à 30 °C`

In [101]:
condition = alea > 30
print(f"Temperatures supérieur a 30 C:\n {alea[condition]}")

Temperatures supérieur a 30 C:
 [43.12800296 34.52652849 34.77288729 43.96398033 32.05758592 39.56838068
 32.16645827 32.26767486 43.44566137 34.29320131 31.83723503 33.01681006
 30.97278651 40.6572981  42.4040193  33.85090359]


`2) Températures « normales » càd comprises entre 20 °C et 30 °C`

In [111]:
condition = np.logical_and(alea > 20, alea < 30)
print(f"Temperatures normales:\n {alea[condition]}")

Temperatures normales:
 [24.26482421 28.67174511 20.57009678 22.06825    26.67439158 28.28922493
 20.540302   23.50622722]


`3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale.
Déterminer anomalies, un tableau de booléen précisant les anomalies`

In [112]:
anomalies = alea >= 35
print(anomalies)

[False  True False False False False  True False  True False False False
  True False False False False False False False  True  True False False]


`4) Le nombre de températures anormales à l’aide de la variable anomalies`

In [117]:
print(f"Nombre de températures anormales: {alea[anomalies].size}")

Nombre de températures anormales: 6


### `Partie 6 – Manipulation des dimensions`

On suppose qu’on a 5 capteurs.

##### `1) Création de façon aléatoire la matrice représentant les températures mesurées par ces capteurs durantune journée`

In [126]:
# Generation des données des 5 capteurs
mes_5_capteurs = rng.uniform(low=20, high=45, size=(5,24))
print(f" {mes_5_capteurs}")


 [[28.35325101 24.32486113 27.84733425 38.56731417 20.36707109 40.67933561
  41.41370059 29.30653933 23.84032248 35.0210102  22.9918139  29.12298403
  43.96072952 44.88661181 39.30262228 27.77403775 37.19162623 37.63515914
  29.69604238 36.02221586 20.26819112 25.22644147 33.12720757 24.09378261]
 [24.1476717  40.90760726 44.72832507 33.8992357  40.97674327 44.75804161
  23.53989721 31.20614033 29.8143179  22.00123209 38.88325432 30.84447568
  31.73317335 23.76682435 24.52316631 42.67759055 21.11622722 25.82130712
  27.30148326 32.25493856 34.66112933 32.3322494  22.10288336 26.09168635]
 [41.08970962 35.93971751 36.22872625 36.75508138 39.07257548 21.45271204
  29.16520962 33.48818588 28.46141208 41.11197183 32.06431271 39.21568974
  41.30038792 32.61978707 42.7388061  34.67809851 41.25685747 28.51476989
  32.47042396 33.28527603 22.6244929  29.96381267 42.93344181 35.77080601]
 [24.43766456 28.47139089 24.79007524 20.62057829 43.18651146 31.20518321
  27.68837681 34.96192979 20.18286

##### `6.2 Transformer la matrice en un tableau unidimensionnel`

In [127]:
mes_5_capteurs_1d = mes_5_capteurs.flatten()
print(mes_5_capteurs_1d)

[28.35325101 24.32486113 27.84733425 38.56731417 20.36707109 40.67933561
 41.41370059 29.30653933 23.84032248 35.0210102  22.9918139  29.12298403
 43.96072952 44.88661181 39.30262228 27.77403775 37.19162623 37.63515914
 29.69604238 36.02221586 20.26819112 25.22644147 33.12720757 24.09378261
 24.1476717  40.90760726 44.72832507 33.8992357  40.97674327 44.75804161
 23.53989721 31.20614033 29.8143179  22.00123209 38.88325432 30.84447568
 31.73317335 23.76682435 24.52316631 42.67759055 21.11622722 25.82130712
 27.30148326 32.25493856 34.66112933 32.3322494  22.10288336 26.09168635
 41.08970962 35.93971751 36.22872625 36.75508138 39.07257548 21.45271204
 29.16520962 33.48818588 28.46141208 41.11197183 32.06431271 39.21568974
 41.30038792 32.61978707 42.7388061  34.67809851 41.25685747 28.51476989
 32.47042396 33.28527603 22.6244929  29.96381267 42.93344181 35.77080601
 24.43766456 28.47139089 24.79007524 20.62057829 43.18651146 31.20518321
 27.68837681 34.96192979 20.18286141 26.95055267 37

##### `6.3 Transposé de la matrice`

In [130]:
print(f"Transposé de la matrice: \n {mes_5_capteurs}")

Transposé de la matrice: 
 [[28.35325101 24.32486113 27.84733425 38.56731417 20.36707109 40.67933561
  41.41370059 29.30653933 23.84032248 35.0210102  22.9918139  29.12298403
  43.96072952 44.88661181 39.30262228 27.77403775 37.19162623 37.63515914
  29.69604238 36.02221586 20.26819112 25.22644147 33.12720757 24.09378261]
 [24.1476717  40.90760726 44.72832507 33.8992357  40.97674327 44.75804161
  23.53989721 31.20614033 29.8143179  22.00123209 38.88325432 30.84447568
  31.73317335 23.76682435 24.52316631 42.67759055 21.11622722 25.82130712
  27.30148326 32.25493856 34.66112933 32.3322494  22.10288336 26.09168635]
 [41.08970962 35.93971751 36.22872625 36.75508138 39.07257548 21.45271204
  29.16520962 33.48818588 28.46141208 41.11197183 32.06431271 39.21568974
  41.30038792 32.61978707 42.7388061  34.67809851 41.25685747 28.51476989
  32.47042396 33.28527603 22.6244929  29.96381267 42.93344181 35.77080601]
 [24.43766456 28.47139089 24.79007524 20.62057829 43.18651146 31.20518321
  27.688

#### `6.4 Les mesures du capteur 1 ;`

In [133]:
print(f"Mesures du capteur 1: \n {mes_5_capteurs[0]}")

Mesures du capteur 1: 
 [28.35325101 24.32486113 27.84733425 38.56731417 20.36707109 40.67933561
 41.41370059 29.30653933 23.84032248 35.0210102  22.9918139  29.12298403
 43.96072952 44.88661181 39.30262228 27.77403775 37.19162623 37.63515914
 29.69604238 36.02221586 20.26819112 25.22644147 33.12720757 24.09378261]


#### `6.5 Extraire toutes les mesures du capteur 5 ;`

In [135]:
print(f"Mesures du capteur 5: \n {mes_5_capteurs[-1]}")

Mesures du capteur 5: 
 [33.82759506 36.35256024 44.24537792 44.61445204 27.20570614 38.34383744
 38.74958845 28.66232153 23.09674437 21.02367401 39.43357819 32.24249355
 44.63850424 31.6243364  44.44792448 30.28940005 39.84205376 22.12048181
 33.88654275 40.05149467 43.11754168 40.56457727 20.92426818 29.31755853]


#### `6.6 Extraire les mesures de tous les capteurs à 10h ;`

In [153]:
print(f"Mesures de tous les capteurs à 10 heurs \n {mes_5_capteurs[:, 9]}")

Mesures de tous les capteurs à 10 heurs 
 [35.0210102  22.00123209 41.11197183 26.95055267 21.02367401]


#### `6.7 Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.`

In [156]:
print(f"Mesures de tous les capteurs à 10 heurs \n {mes_5_capteurs[2:5, 8:13]}")

Mesures de tous les capteurs à 10 heurs 
 [[28.46141208 41.11197183 32.06431271 39.21568974 41.30038792]
 [20.18286141 26.95055267 37.57583664 35.84424433 44.54514869]
 [23.09674437 21.02367401 39.43357819 32.24249355 44.63850424]]


### `Partie 7 – Concaténation`

On suppose qu’on a un 2nd bâtiment avec 3 capteurs.

##### `7.1 Matricereprésentant les températures mesurées par les 3 capteurs durant une journée`

In [157]:
# Generation des données des 3 capteurs du 3 eme etages
mes_3_capteurs = rng.uniform(low=20, high=45, size=(3,24))
print(f" {mes_3_capteurs}")

 [[21.21746181 22.73205728 36.88264072 37.83145491 39.34301707 41.6364137
  38.48578671 40.0217898  21.22409275 25.86337876 35.54744433 41.45313262
  20.11250312 32.86573355 36.93218498 20.74018223 30.03388894 42.39087203
  36.79032022 25.94145908 41.31952824 28.70078559 41.33361678 27.47359128]
 [34.75800627 29.92350169 26.87062627 42.16393905 24.68984205 22.12028978
  28.54817346 37.94097869 40.18579015 44.96858425 27.40905143 30.19854878
  23.42053195 34.37179824 44.93950093 37.52202525 34.88032101 29.80922732
  42.88246901 32.4229149  23.35917283 29.13446158 21.67916672 25.04947594]
 [20.44171952 31.33199791 35.86350662 28.58231156 30.50954429 43.98023182
  38.79907804 33.52141592 27.11352188 42.42491997 25.87742792 28.13356826
  42.72662036 33.23855138 38.55794874 34.76861985 36.33598023 27.48458229
  26.03430154 28.06230868 23.8860391  41.85785913 27.08117333 34.03723486]]


##### ` 7.2 Deux methodes différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée`

`Methode 1: concatenate()`

In [158]:
mes_8_capteurs = np.concatenate((mes_5_capteurs, mes_3_capteurs))
print(mes_8_capteurs)

[[28.35325101 24.32486113 27.84733425 38.56731417 20.36707109 40.67933561
  41.41370059 29.30653933 23.84032248 35.0210102  22.9918139  29.12298403
  43.96072952 44.88661181 39.30262228 27.77403775 37.19162623 37.63515914
  29.69604238 36.02221586 20.26819112 25.22644147 33.12720757 24.09378261]
 [24.1476717  40.90760726 44.72832507 33.8992357  40.97674327 44.75804161
  23.53989721 31.20614033 29.8143179  22.00123209 38.88325432 30.84447568
  31.73317335 23.76682435 24.52316631 42.67759055 21.11622722 25.82130712
  27.30148326 32.25493856 34.66112933 32.3322494  22.10288336 26.09168635]
 [41.08970962 35.93971751 36.22872625 36.75508138 39.07257548 21.45271204
  29.16520962 33.48818588 28.46141208 41.11197183 32.06431271 39.21568974
  41.30038792 32.61978707 42.7388061  34.67809851 41.25685747 28.51476989
  32.47042396 33.28527603 22.6244929  29.96381267 42.93344181 35.77080601]
 [24.43766456 28.47139089 24.79007524 20.62057829 43.18651146 31.20518321
  27.68837681 34.96192979 20.182861

`Methode 2: vstack()`

In [160]:
mes_8_capteurs = np.vstack((mes_5_capteurs, mes_3_capteurs))
print(mes_8_capteurs)

[[28.35325101 24.32486113 27.84733425 38.56731417 20.36707109 40.67933561
  41.41370059 29.30653933 23.84032248 35.0210102  22.9918139  29.12298403
  43.96072952 44.88661181 39.30262228 27.77403775 37.19162623 37.63515914
  29.69604238 36.02221586 20.26819112 25.22644147 33.12720757 24.09378261]
 [24.1476717  40.90760726 44.72832507 33.8992357  40.97674327 44.75804161
  23.53989721 31.20614033 29.8143179  22.00123209 38.88325432 30.84447568
  31.73317335 23.76682435 24.52316631 42.67759055 21.11622722 25.82130712
  27.30148326 32.25493856 34.66112933 32.3322494  22.10288336 26.09168635]
 [41.08970962 35.93971751 36.22872625 36.75508138 39.07257548 21.45271204
  29.16520962 33.48818588 28.46141208 41.11197183 32.06431271 39.21568974
  41.30038792 32.61978707 42.7388061  34.67809851 41.25685747 28.51476989
  32.47042396 33.28527603 22.6244929  29.96381267 42.93344181 35.77080601]
 [24.43766456 28.47139089 24.79007524 20.62057829 43.18651146 31.20518321
  27.68837681 34.96192979 20.182861

#### `Partie 8 : Calcul scientifique`

Considérons le tableau représentant les 24 températures du 1er bâtiment.


##### `8.1 Pour les températures on calcule:`
- le minimum, 
- le maximum, 
- la somme, 
- la moyenne, 
- la médiane, 
- la variance et 
- l’écart-type

`Le minimum: `

In [202]:
# On calcule le minimum pour chaque capteur parmis les 5
mes_24_heures = mes_5_capteurs[0]
print(f"Les minimums: {np.min(mes_24_heures)}")

Les minimums: 20.268191124391905


`Le maximum:`

In [203]:
print(f"Les maximums: {np.max(mes_24_heures)}")

Les maximums: 44.88661181459093


`La somme: `

In [204]:
print(f"Les sommes: {np.sum(mes_24_heures)}")

Les sommes: 761.0202055244822


`La moyenne:`

In [205]:
print(f"Les moyennes: {np.mean(mes_24_heures)}")

Les moyennes: 31.70917523018676


`La mediane:`

In [206]:
print(f"Les mediannes: {np.median(mes_24_heures)}")

Les mediannes: 29.501290854439972


`La variance:`

In [208]:
print(f"Les variances: {np.var(mes_24_heures)}")

Les variances: 54.58380692576784


`L'ecart-type:`

In [209]:
print(f"Les ecart-type: {np.std(mes_24_heures)}")

Les ecart-type: 7.38808547093006


##### `8.2 Standardisation du tableau des températures`

In [216]:
moyennes = np.mean(mes_24_heures)
ecart_type = np.std(mes_24_heures)

mes_24_heures_standar = (mes_24_heures - moyennes) / (ecart_type )
print(mes_24_heures_standar)
print(f"Moyenne après standardisation: \n  {np.round(np.mean(mes_24_heures_standar))}")
print(f"Ecart-type après standardisation: \n  {np.round(np.std(mes_24_heures_standar))}")


[-0.45423462 -0.99948953 -0.52271201  0.92827011 -1.53518854  1.21413869
  1.31353723 -0.32520413 -1.06507332  0.44826701 -1.17992156 -0.3500489
  1.6582854   1.78360641  1.02779632 -0.53263291  0.74206654  0.80210007
 -0.2724837   0.58378326 -1.54857225 -0.87745787  0.19193502 -1.03076672]
Moyenne après standardisation: 
  0.0
Ecart-type après standardisation: 
  1.0


##### `8.3 Normalisation du tableau des températures`

In [ ]:
x_min = np.min(mes_24_heures)
x_max = np.max(mes_24_heures)

mes_normaliser = (mes_24_heures - x_min) / (x_max - x_min)

print(mes_normaliser)

[0.32841505 0.16478189 0.30786472 0.74331019 0.0040165  0.82910048
 0.85893038 0.36713761 0.14509994 0.59925936 0.11063353 0.3596816
 0.96239067 1.         0.7731784  0.30488741 0.68742976 0.70544607
 0.38295922 0.63992833 0.         0.20140408 0.52233312 0.15539549]
0.464732658921118


##### `8.4 Convertion le tableau initial en Fahrenheit`

In [218]:
# conversion en farenheit

temps_convertis_f = (temps_24_heures * 1.8) + 32
print(f"Valeurs convertis en Farenheit: \n {temps_convertis_f}")


Valeurs convertis en Farenheit: 
 [32.  33.8 35.6 37.4 39.2 41.  42.8 44.6 46.4 48.2 50.  51.8 53.6 55.4
 57.2 59.  60.8 62.6 64.4 66.2 68.  69.8 71.6 73.4]


### `Partie 9 : Broadcasting`

##### `9.1 Création de façon aléatoire de la matrice temperatures_3x3 représentant les températures mesurées à 10h, 11h et 12h dans le 2nd bâtiment`

In [228]:
temperatures_3x3 = rng.uniform(low=20, high=40, size=(3,3))
temperatures_3x3

array([[26.44980882, 24.84965706, 29.59726801],
       [33.66516715, 24.56505751, 26.61471484],
       [38.60769235, 20.9713858 , 29.2153921 ]])

#### `9.2 On suppose que les valeurs de calibration des capteurs soient stockées dans le tableau correction = np.array([1, -0.5, 0.2]).`
`Application des corrections pour trouver les mesures corrigées`
`mesures_corrigees = temperatures_3x3 + correction`

In [230]:
correction = np.array([1, -0.5, 0.2])
mesures_corrigees = temperatures_3x3 + correction
mesures_corrigees

array([[27.44980882, 24.34965706, 29.79726801],
       [34.66516715, 24.06505751, 26.81471484],
       [39.60769235, 20.4713858 , 29.4153921 ]])