# `=== Atelier Numpy ===`

### `=== Contexte ===`

Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales

### `=== Partie 1 : Listes Python vs tableaux NumPy ===`

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

##### `1.1 Création d'une liste Python stockant ces températures`

In [2]:
# liste standard de python
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8]
print("liste stadard de python:")
print(temperatures)

liste stadard de python:
[24.5, 25.1, 26.3, 27.0, 25.8]


##### `=== 1.2 Création d'un tableau NumPy équivalent stockant ces températures ===`

In [6]:
import numpy as np

# tableau numpy
numpy_tableau = np.array(temperatures)
print("Tableau numpy")
print(numpy_tableau)

Tableau numpy
[24.5 25.1 26.3 27.  25.8]


##### `=== 1.3 Multiplication par 2 sur ces deux collections === `

In [21]:
import time

# Multiplication avec la liste pyrthon (boucle for)
start_time1 = time.time()
temperature_x2 = []
for temp in temperatures:
     temperature_x2.append(temp * 2)

print(f"Multiplication avec les listes python: \n {temperatures_x2} \n Temps d'execution: {time.time() - start_time1:.6f} \n") 

# Multiplication avec les tableaux numpy (operation vectoriel)
start_time2 = time.time()
print(f"Multiplication du tableau numpy: \n {numpy_tableau*2} \n Temps d'execution {time.time() - start_time2:.6f}")

Multiplication avec les listes python: 
 [49.0, 50.2, 52.6, 54.0, 51.6] 
 Temps d'execution: 0.000097 

Multiplication du tableau numpy: 
 [49.  50.2 52.6 54.  51.6] 
 Temps d'execution 0.000257


#### `=== 1.4 Observation ===`

On constate qu'avec le calcul sur les listes standards de python, pour ce cas, que la durée d'execution est plus courte qu'avec le tableau `NumPy` mais en terme ligne de code, la multiplication avec le tableau numpy est beaucoup plus optimisé (1 ligne)

### `=== Partie 2 – Création des données ===`

##### `2.1 Tableau représentant les mesures de température de 10 capteurs, initialement à zéro`

In [25]:
# Numpy deja importé en haut !
temps_10_capteurs_0 = np.zeros(10)
print(temps_10_capteurs_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### `2.2  Création d'un tableau contenant 10 valeurs égales à 1.`

In [26]:
# Numpy deja importé en haut !
temps_10_capteurs_1 = np.ones(10)
print(temps_10_capteurs_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### `2.3 Création d'un tableau de 10 valeurs initialisées à 25.`

In [34]:
temps_10_capteurs_25 = np.full((10), 25)
print(temps_10_capteurs_25)

[25 25 25 25 25 25 25 25 25 25]


#### `3.4 Création  d'une matrice identité de taille 5 × 5.`

In [35]:
identite = np.eye(5)
print(identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### `3.5 Création des 24 heures (de 0 à 23) de mesure d'une journée`

In [36]:
temps_24_heures = np.arange(24)
print(temps_24_heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


##### `3.6 Création de 10 valeurs régulièrement réparties entre 20 °C et 30 °C`

In [38]:
temps_20_40_c = np.linspace(20, 30, 10)
print(temps_20_40_c)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


##### `3.7 Création de 100 mesures de températures aleatoires, reproductible`

In [41]:
from numpy import random

# On fixe la graine (seed) pour rendre le resultat reproductible
rng = np.random.default_rng(seed=42)
# On genere 100 temperatures 
temperatures_alea = rng.uniform(low=20, high=30, size=100)
print(temperatures_alea)

[27.73956049 24.3887844  28.5859792  26.97368029 20.94177348 29.75622352
 27.61139702 27.86064305 21.28113633 24.50385938 23.70798024 29.26764989
 26.4386512  28.22761613 24.43414199 22.27238722 25.54584787 20.63817256
 28.27631172 26.31664399 27.5808774  23.54525968 29.70698024 28.93121121
 27.78383497 21.94638708 24.66721004 20.43803766 21.54289492 26.83048953
 27.44762156 29.67509732 23.25825358 23.70459706 24.69555811 21.89471359
 21.29921505 24.75704926 22.26909349 26.69813995 24.37151919 28.32678196
 27.00265102 23.12366641 28.32259801 28.04764357 23.87478379 22.88328104
 26.82495504 21.39752484 21.99908202 20.0736227  27.86924378 26.64850857
 27.05165379 27.80729031 24.58915776 25.68741196 21.39796998 21.14530074
 26.68402962 24.71096206 25.65236106 27.64998857 26.3471832  25.53579401
 25.59207161 23.03950098 20.30817835 24.36717389 22.14584673 24.08528644
 28.53403073 22.33939486 20.58302742 22.81383892 22.93593758 26.61916515
 25.57032152 27.83898209 26.6431354  24.06386861 28

#### `Partie 3 – Exploration des tableaux`

##### `3.1 Créeation d'un tableau représentant les 24 températures d'une journée de façon aléatoire :`

In [42]:
alea = np.random.random(24)
print(alea)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333 0.89132195 0.20920212
 0.18532822 0.10837689 0.21969749 0.97862378 0.81168315 0.17194101
 0.81622475 0.27407375 0.43170418 0.94002982 0.81764938 0.33611195]


##### `3.2 Propriétes du tableau`

`a) nombre de dimensions ;`

In [47]:
print(f"Nombre de dimension: {alea.ndim}")

Nombre de dimension: 1


`b) nombre de valeurs ;`

In [48]:
print(f"Nombre de valeur: {alea.size}")

Nombre de valeur: 24


`c) type des données ;`

In [49]:
print(f"Type des données: {alea.dtype}")

Type des données: float64


`d) forme du tableau.`

In [50]:
print(f"Forme du tableau: {alea.shape}")

Forme du tableau: (24,)
